// This file is auto-generated by @hey-api/openapi-ts

export const ModelPublicSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            example: 1
        },
        rel_id: {
            type: 'integer',
            example: 1
        },
        name: {
            type: 'string',
            example: 'Name 1'
        }
    },
    required: ['id', 'rel_id', 'name']
} as const;

export const RelModelPublicSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            example: 101
        },
        name: {
            type: 'string',
            example: 'Name'
        }
    },
    required: ['id', 'name']
} as const;