// This file is auto-generated by @hey-api/openapi-ts

export const ItemPublicSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            example: 1
        },
        name: {
            type: 'string',
            example: 'Name 1'
        },
        rel_id: {
            type: 'integer',
            example: 1
        }
    },
    required: ['id', 'name', 'rel_id']
} as const;

export const ItemsPublicSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'ItemPublic[]'
        },
        count: {
            type: 'integer'
        }
    },
    required: ['data', 'count']
} as const;

export const RelItemPublicSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            example: 101
        },
        name: {
            type: 'string',
            example: 'Rel Name'
        }
    },
    required: ['id', 'name']
} as const;

export const RelItemsPublicSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'RelItemPublic[]'
        },
        count: {
            type: 'integer'
        }
    },
    required: ['data', 'count']
} as const;