// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ReadItemsResponse, CreateItemData, CreateItemResponse, ReadItemData, ReadItemResponse, UpdateItemData, UpdateItemResponse, DeleteItemData, DeleteItemResponse, ReadRelItemsResponse } from './types.gen';

export class ItemService {
    /**
     * Get all items
     * @returns ItemsPublic List of items
     * @throws ApiError
     */
    public static readItems(): CancelablePromise<ReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items'
        });
    }
    
    /**
     * Create a new item
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Item created
     * @throws ApiError
     */
    public static createItem(data: CreateItemData): CancelablePromise<CreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Get one item
     * @param data The data for the request.
     * @param data.id ID of the item to fetch
     * @returns ItemPublic Item found
     * @throws ApiError
     */
    public static readItem(data: ReadItemData): CancelablePromise<ReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * Update an item
     * @param data The data for the request.
     * @param data.id ID of the item to update
     * @param data.requestBody
     * @returns ItemPublic Item updated
     * @throws ApiError
     */
    public static updateItem(data: UpdateItemData): CancelablePromise<UpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Delete an item
     * @param data The data for the request.
     * @param data.id ID of the item to delete
     * @returns ItemPublic Item deleted
     * @throws ApiError
     */
    public static deleteItem(data: DeleteItemData): CancelablePromise<DeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            }
        });
    }
    
}

export class RelItemService {
    /**
     * Get all rel items
     * @returns RelItemsPublic List of rel items
     * @throws ApiError
     */
    public static readRelItems(): CancelablePromise<ReadRelItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rel_items'
        });
    }
    
}