// This file is auto-generated by @hey-api/openapi-ts

export type ItemPublic = {
    id: number;
    name: string;
    rel_id: number;
};

export type ItemsPublic = {
    data: ItemPublic;
    count: number;
};

export type RelItemPublic = {
    id: number;
    name: string;
};

export type RelItemsPublic = {
    data: RelItemPublic;
    count: number;
};

export type ReadItemsResponse = (ItemsPublic);

export type CreateItemData = {
    requestBody: ItemPublic;
};

export type CreateItemResponse = (ItemPublic);

export type ReadItemData = {
    /**
     * ID of the item to fetch
     */
    id: number;
};

export type ReadItemResponse = (ItemPublic);

export type UpdateItemData = {
    /**
     * ID of the item to update
     */
    id: number;
    requestBody: ItemPublic;
};

export type UpdateItemResponse = (ItemPublic);

export type DeleteItemData = {
    /**
     * ID of the item to delete
     */
    id: number;
};

export type DeleteItemResponse = (ItemPublic);

export type ReadRelItemsResponse = (RelItemsPublic);