// This file is auto-generated by @hey-api/openapi-ts

export type ModelPublic = {
    id: number;
    rel_id: number;
    name: string;
};

export type RelModelPublic = {
    id: number;
    name: string;
};

export type GetApiV1ModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/models';
};

export type GetApiV1ModelsResponses = {
    /**
     * List of models
     */
    200: Array<ModelPublic>;
};

export type GetApiV1ModelsResponse = GetApiV1ModelsResponses[keyof GetApiV1ModelsResponses];

export type GetApiV1RelModelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rel_model';
};

export type GetApiV1RelModelResponses = {
    /**
     * List of items
     */
    200: Array<RelModelPublic>;
};

export type GetApiV1RelModelResponse = GetApiV1RelModelResponses[keyof GetApiV1RelModelResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};